const KEY='sigprod_pmesp_local_v1';
let state=loadState();
let editingPM=null, editingLanc=null;
const principais=['Pessoas','Carros','Motos','Ônibus','Caminhões','Condutores','Moto Apree.','Veiculos Apre.','AI Confec.','Presos','Mandados','Armas Fogo','Arma Branca','Tráfico','Porte','Apree. Drogas','BOPM Elabo.','Oc. Atendida'];
function clone(o){return JSON.parse(JSON.stringify(o))}
function loadState(){const raw=localStorage.getItem(KEY); if(raw) return JSON.parse(raw); return clone(window.SIGPROD_SEED)}
function persist(){localStorage.setItem(KEY,JSON.stringify(state)); refreshAll()}
function br(n){return Number(n||0).toLocaleString('pt-BR')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function today(){return new Date().toISOString().slice(0,10)}
function monthStart(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===id));refreshAll()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function activePMs(){return [...state.efetivo].filter(p=>p.status==='ATIVO').sort((a,b)=>String(a.qra).localeCompare(String(b.qra)))}
function allTipos(){return [...new Set([...(state.tipos||[]),...state.lancamentos.map(x=>x.tipo).filter(Boolean)])].filter(x=>x&&x!=='#N/A').sort()}
function allEquipes(){return [...new Set([...(state.equipes||[]),...state.efetivo.map(p=>p.equipe).filter(Boolean),...state.lancamentos.map(x=>x.equipe).filter(Boolean)])].sort()}
function setSelect(id,arr,all='Todos'){const el=document.getElementById(id); if(!el) return; const val=el.value; el.innerHTML=`<option value="">${all}</option>`+arr.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join(''); if([...el.options].some(o=>o.value===val)) el.value=val}
function fillSelects(){const pols=activePMs().map(p=>({v:p.qra,t:`${p.grad} ${p.qra}`})); ['fPol'].forEach(id=>{const el=document.getElementById(id); if(el){const val=el.value; el.innerHTML='<option value="">Todos</option>'+pols.map(p=>`<option value="${esc(p.v)}">${esc(p.t)}</option>`).join(''); el.value=val}}); ['fTipo','dashTipo','rTipo'].forEach(id=>setSelect(id,allTipos(),'Todos')); setSelect('fEquipe',allEquipes(),'Todas')}
function buildLancForm(){const f=document.getElementById('formLanc'); if(!f) return; const metrics=principais.filter(m=>state.metricas.includes(m)); f.innerHTML=`<label>Data do serviço<input type="date" id="lData" required></label><label>Policial<select id="lPol"></select></label><label>Tipo de policiamento<select id="lTipo"></select></label><label>Equipe/Viatura<input id="lEquipe" placeholder="Ex.: RP, DEJEM, Equipe A"></label>`+metrics.map(m=>`<label>${esc(m)}<input type="number" min="0" value="0" id="m_${cssId(m)}"></label>`).join('')+`<label style="grid-column:1/-1">Observações<textarea id="lObs" placeholder="Observações do relatório de serviço"></textarea></label>`; document.getElementById('lData').value=today(); document.getElementById('lPol').innerHTML=activePMs().map(p=>`<option value="${esc(p.qra)}" data-re="${esc(p.re)}">${esc(p.grad+' '+p.qra)}</option>`).join(''); document.getElementById('lTipo').innerHTML=allTipos().map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('')}
function cssId(s){return s.replace(/[^a-z0-9]/gi,'_')}
function clearLanc(){editingLanc=null; buildLancForm()}
document.getElementById('novoLanc').onclick=clearLanc;
document.getElementById('salvarLanc').onclick=e=>{e.preventDefault(); const sel=document.getElementById('lPol'); if(!sel.value){alert('Selecione o policial.');return} const rec= editingLanc ? state.lancamentos.find(x=>x.id===editingLanc) : {id:String(Date.now())}; rec.data=lData.value; rec.tipo=lTipo.value; rec.re=sel.selectedOptions[0]?.dataset.re||''; rec.qra=sel.value; rec.equipe=lEquipe.value; rec.observacao=lObs.value; rec.cadastro=today(); state.metricas.forEach(m=>{const el=document.getElementById('m_'+cssId(m)); if(el) rec[m]=Number(el.value||0)}); if(!editingLanc) state.lancamentos.push(rec); editingLanc=null; persist(); alert('Lançamento salvo.')}
function editLanc(id){const r=state.lancamentos.find(x=>x.id==id); if(!r) return; showPage('lancar'); editingLanc=String(id); lData.value=r.data||today(); lTipo.value=r.tipo||''; lPol.value=r.qra||''; lEquipe.value=r.equipe||''; lObs.value=r.observacao||''; state.metricas.forEach(m=>{const el=document.getElementById('m_'+cssId(m)); if(el) el.value=Number(r[m]||0)})}
function delLanc(id){if(confirm('Excluir este lançamento?')){state.lancamentos=state.lancamentos.filter(x=>x.id!=id);persist()}}
function between(r,ini,fim,tipo,pol,equipe){return (!ini||r.data>=ini)&&(!fim||r.data<=fim)&&(!tipo||r.tipo===tipo)&&(!pol||r.qra===pol)&&(!equipe||r.equipe===equipe)}
function dataConsulta(){return state.lancamentos.filter(r=>between(r,fIni.value,fFim.value,fTipo.value,fPol.value,fEquipe.value))}
function dataDash(){return state.lancamentos.filter(r=>between(r,dashIni.value,dashFim.value,dashTipo.value,'',''))}
function dataRank(){return state.lancamentos.filter(r=>between(r,rIni.value,rFim.value,rTipo.value,'',''))}
function sum(arr,field){return arr.reduce((a,r)=>a+Number(r[field]||0),0)}
function table(id,heads,rows){const el=document.getElementById(id); if(!el) return; el.innerHTML='<thead><tr>'+heads.map(h=>`<th>${esc(h)}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>`<td>${c}</td>`).join('')+'</tr>').join('')+'</tbody>'}
function group(arr,key,fields){const m={}; arr.forEach(r=>{const k=r[key]||'Sem informação'; if(!m[k]){m[k]={reg:0}; fields.forEach(f=>m[k][f]=0)} m[k].reg++; fields.forEach(f=>m[k][f]+=Number(r[f]||0))}); return m}
function rank(arr,field,limit=15){const g=group(arr,'qra',[field]); return Object.entries(g).sort((a,b)=>b[1][field]-a[1][field]).slice(0,limit).map(([k,v],i)=>[i+1,esc(k),br(v[field])])}
function countRank(arr,limit=15){const m={}; arr.forEach(r=>m[r.qra]=(m[r.qra]||0)+1); return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,limit).map(([k,v],i)=>[i+1,esc(k),br(v)])}
function cards(id,arr){document.getElementById(id).innerHTML=arr.map(c=>`<div class="card"><span>${esc(c[0])}</span><strong>${br(c[1])}</strong></div>`).join('')}
function refreshDashboard(){const d=dataDash(); cards('dashCards',[['Registros',d.length],['Pessoas',sum(d,'Pessoas')],['Veículos',sum(d,'Carros')+sum(d,'Motos')+sum(d,'Ônibus')+sum(d,'Caminhões')],['AI confeccionados',sum(d,'AI Confec.')],['Presos',sum(d,'Presos')],['BOPM',sum(d,'BOPM Elabo.')]]); table('dashRankPessoas',['#','Policial','Pessoas'],rank(d,'Pessoas',10)); table('dashRankAparece',['#','Policial','Lançamentos'],countRank(d,10)); barChart('chartTipo',Object.entries(group(d,'tipo',['Pessoas'])).map(([k,v])=>[k,v.Pessoas]).sort((a,b)=>b[1]-a[1]).slice(0,12)); const mes={}; d.forEach(r=>{const k=(r.data||'').slice(0,7); if(k) mes[k]=(mes[k]||0)+Number(r.Pessoas||0)}); barChart('chartMes',Object.entries(mes).sort().slice(-12));}
function barChart(id,items){const max=Math.max(1,...items.map(x=>x[1])); document.getElementById(id).innerHTML=items.map(([k,v])=>`<div class="barrow"><div class="barlabel" title="${esc(k)}">${esc(k)}</div><div class="bartrack"><div class="barfill" style="width:${Math.max(2,(v/max)*100)}%"></div></div><div class="barval">${br(v)}</div></div>`).join('') || '<p>Sem dados no período.</p>'}
function refreshConsultas(){const d=dataConsulta(); cards('relCards',[['Registros',d.length],['Pessoas',sum(d,'Pessoas')],['Carros',sum(d,'Carros')],['Motos',sum(d,'Motos')],['Presos',sum(d,'Presos')],['Mandados',sum(d,'Mandados')],['AI',sum(d,'AI Confec.')],['BOPM',sum(d,'BOPM Elabo.')],['Ocorrências',sum(d,'Oc. Atendida')],['Drogas',sum(d,'Apree. Drogas')],['Armas fogo',sum(d,'Armas Fogo')],['Tráfico',sum(d,'Tráfico')]]); const fields=['Pessoas','Carros','Motos','AI Confec.','Presos','BOPM Elabo.']; const gp=group(d,'qra',fields); table('resumoPolicial',['Policial','Reg.','Pessoas','Carros','Motos','AI','Presos','BOPM'],Object.entries(gp).sort((a,b)=>b[1].Pessoas-a[1].Pessoas).map(([k,v])=>[esc(k),v.reg,br(v.Pessoas),br(v.Carros),br(v.Motos),br(v['AI Confec.']),br(v.Presos),br(v['BOPM Elabo.'])])); const gt=group(d,'tipo',fields); table('resumoTipo',['Tipo','Reg.','Pessoas','Carros','Motos','AI','Presos','BOPM'],Object.entries(gt).sort((a,b)=>b[1].reg-a[1].reg).map(([k,v])=>[esc(k),v.reg,br(v.Pessoas),br(v.Carros),br(v.Motos),br(v['AI Confec.']),br(v.Presos),br(v['BOPM Elabo.'])])); table('registros',['Data','Tipo','RE','QRA','Equipe','Pessoas','Carros','Motos','AI','Presos','BOPM','Ações'],d.slice(-1000).reverse().map(r=>[esc(r.data),esc(r.tipo),esc(r.re),esc(r.qra),esc(r.equipe),br(r.Pessoas),br(r.Carros),br(r.Motos),br(r['AI Confec.']),br(r.Presos),br(r['BOPM Elabo.']),`<button onclick="editLanc('${r.id}')">Editar</button> <button class="danger" onclick="delLanc('${r.id}')">Excluir</button>`]));}
function refreshRankings(){const d=dataRank(); const fields=['Pessoas','Carros','Motos','Condutores','AI Confec.','Presos','Mandados','Armas Fogo','Tráfico','Apree. Drogas','BOPM Elabo.','Oc. Atendida']; document.getElementById('rankingGrid').innerHTML=fields.map(f=>`<div class="panel"><h3>${esc(f)}</h3><table id="rank_${cssId(f)}"></table></div>`).join(''); fields.forEach(f=>table('rank_'+cssId(f),['#','Policial','Total'],rank(d,f,10))) }
function refreshEfetivo(){table('tEfetivo',['Grad','RE','QRA','Equipe','Status','Ações'],state.efetivo.map((p,i)=>[esc(p.grad),esc(p.re),esc(p.qra),esc(p.equipe||''),`<span class="pill">${esc(p.status)}</span>`,`<button onclick="editPM(${i})">Editar</button> <button onclick="statusPM(${i},'TRANSFERIDO')">Transferido</button> <button onclick="statusPM(${i},'ATIVO')">Ativar</button>`]))}
function editPM(i){const p=state.efetivo[i]; editingPM=i; pmGrad.value=p.grad; pmRE.value=p.re; pmQRA.value=p.qra; pmEquipe.value=p.equipe||''; pmStatus.value=p.status}
function statusPM(i,s){state.efetivo[i].status=s; persist()}
document.getElementById('salvarPM').onclick=e=>{e.preventDefault(); const p={id:String(Date.now()),grad:pmGrad.value.trim(),re:pmRE.value.trim(),qra:pmQRA.value.trim().toUpperCase(),equipe:pmEquipe.value.trim(),status:pmStatus.value}; if(!p.qra){alert('Informe o QRA.'); return} if(editingPM!==null){state.efetivo[editingPM]=p; editingPM=null}else state.efetivo.push(p); pmGrad.value=pmRE.value=pmQRA.value=pmEquipe.value=''; pmStatus.value='ATIVO'; persist()}
function refreshUltimos(){table('ultimos',['Data','Tipo','QRA','Pessoas','Carros','Motos','BOPM'],state.lancamentos.slice(-25).reverse().map(r=>[esc(r.data),esc(r.tipo),esc(r.qra),br(r.Pessoas),br(r.Carros),br(r.Motos),br(r['BOPM Elabo.'])]))}
function download(name,text,type='text/plain'){const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type})); a.download=name; a.click()}
function csvFrom(rows){const cols=['data','tipo','re','qra','equipe',...principais.filter(m=>state.metricas.includes(m)),'observacao']; return cols.join(';')+'\n'+rows.map(r=>cols.map(c=>String(r[c]??'').replaceAll(';',',').replaceAll('\n',' ')).join(';')).join('\n')}
exportarJson.onclick=()=>download('backup_SIGPROD.json',JSON.stringify(state,null,2),'application/json');
exportarTudoCsv.onclick=()=>download('lancamentos_SIGPROD.csv',csvFrom(state.lancamentos),'text/csv');
btnCsv.onclick=()=>download('relatorio_filtrado_SIGPROD.csv',csvFrom(dataConsulta()),'text/csv');
importJson.onchange=e=>{const f=e.target.files[0]; if(!f) return; const rd=new FileReader(); rd.onload=()=>{state=JSON.parse(rd.result); persist(); alert('Backup importado.')}; rd.readAsText(f)};
resetar.onclick=()=>{if(confirm('Restaurar a base inicial importada do Excel? Isso não apaga o backup que você já exportou.')){localStorage.removeItem(KEY); state=clone(window.SIGPROD_SEED); refreshAll()}}
dashAtualizar.onclick=refreshDashboard; btnFiltrar.onclick=refreshConsultas; rAtualizar.onclick=refreshRankings;
function initDates(){['dashIni','fIni','rIni'].forEach(id=>{const el=document.getElementById(id); if(el&&!el.value) el.value=monthStart()}); ['dashFim','fFim','rFim'].forEach(id=>{const el=document.getElementById(id); if(el&&!el.value) el.value=today()})}
function refreshAll(){fillSelects(); if(!document.getElementById('formLanc').children.length) buildLancForm(); refreshDashboard(); refreshConsultas(); refreshRankings(); refreshEfetivo(); refreshUltimos()}
initDates(); refreshAll(); if('serviceWorker' in navigator) navigator.serviceWorker.register('service-worker.js').catch(()=>{});
